<?php

$CATEGORIES = [
	'van-phong' => ['name' => 'Văn phòng', 'order' => 1],
	'mang'      => ['name' => 'Mạng', 'order' => 2],
	'tien-ich'  => ['name' => 'Tiện ích', 'order' => 3],
	'media'     => ['name' => 'Media', 'order' => 4],
	'bao-mat'   => ['name' => 'Bảo mật', 'order' => 5],
];

$SOFTWARE = [
	[
		'id'       => 'onlyoffice',
		'name'     => 'ONLYOFFICE',
		'cat'      => 'van-phong',
		'desc'     => 'Bộ ứng dụng văn phòng mã nguồn mở, tương thích mạnh mẽ với Microsoft Office. Hoàn toàn miễn phí.',
		'intro'    => "ONLYOFFICE là bộ ứng dụng văn phòng mã nguồn mở, hoàn toàn miễn phí, cho phép bạn làm việc với các tài liệu văn bản, bảng tính và bài thuyết trình. Điểm mạnh của ONLYOFFICE là khả năng tương thích cao với định dạng Microsoft Office (DOCX, XLSX, PPTX), giúp bạn dễ dàng mở và chỉnh sửa các file từ Microsoft Office mà không lo mất định dạng.\n\nPhần mềm có sẵn cho Windows, macOS, Linux và cả phiên bản trực tuyến. Giao diện trực quan, quen thuộc giúp người dùng dễ dàng làm quen và sử dụng. ONLYOFFICE còn hỗ trợ làm việc cộng tác trực tuyến theo thời gian thực.",
		'url'      => 'https://www.onlyoffice.com/',
		'download' => 'https://www.onlyoffice.com/download-desktop.aspx',
	],
	[
		'id'       => 'unikey',
		'name'     => 'Unikey',
		'cat'      => 'van-phong',
		'desc'     => 'Bộ gõ tiếng Việt phổ biến nhất trên Windows. Nhỏ gọn, miễn phí, hỗ trợ mọi kiểu gõ.',
		'intro'    => "Unikey là bộ gõ tiếng Việt mã nguồn mở, nhỏ gọn và cực kỳ phổ biến tại Việt Nam. Đây là phần mềm không thể thiếu trên bất kỳ máy tính Windows nào của người Việt.\n\nVới Unikey, bạn có thể gõ tiếng Việt trong bất kỳ ứng dụng Windows nào một cách dễ dàng. Phần mềm hỗ trợ tất cả các kiểu gõ phổ biến như Telex, VNI, VIQR và nhiều bảng mã khác nhau. Unikey còn tích hợp công cụ chuyển đổi font chữ tiện lợi, giúp bạn chuyển đổi văn bản giữa các bảng mã một cách nhanh chóng.",
		'url'      => 'https://unikey.org/',
		'download' => 'https://unikey.org/download.html',
	],
	[
		'id'       => 'foxit-pdf-reader',
		'name'     => 'Foxit PDF Reader',
		'cat'      => 'van-phong',
		'desc'     => 'Trình đọc và chỉnh sửa PDF nhẹ, nhanh, giàu tính năng thay thế Adobe Reader.',
		'intro'    => "Foxit PDF Reader là trình đọc PDF nhẹ và nhanh, là sự thay thế tuyệt vời cho Adobe Reader. Phần mềm khởi động nhanh, tiêu tốn ít tài nguyên hệ thống và có đầy đủ các tính năng cần thiết.\n\nBạn có thể xem, ký tên, đánh dấu, gạch chân và chú thích trên file PDF một cách dễ dàng. Foxit PDF Reader còn hỗ trợ điền form, bảo vệ file PDF bằng mật khẩu và tích hợp với các dịch vụ lưu trữ đám mây như Google Drive, OneDrive.",
		'url'      => 'https://www.foxit.com/pdf-reader/',
		'download' => 'https://www.foxit.com/downloads/',
	],
	[
		'id'       => 'thunderbird',
		'name'     => 'Thunderbird',
		'cat'      => 'van-phong',
		'desc'     => 'Ứng dụng email và quản lý lịch làm việc miễn phí từ Mozilla. Mạnh mẽ, bảo mật, không quảng cáo.',
		'intro'    => "Mozilla Thunderbird là ứng dụng email mã nguồn mở, mạnh mẽ và bảo mật, được phát triển bởi Mozilla – tổ chức đứng sau Firefox.\n\nThunderbird hỗ trợ quản lý nhiều tài khoản email cùng lúc, lọc thư thông minh, tích hợp lịch làm việc và sổ địa chỉ. Bạn có thể quản lý email từ Gmail, Outlook, Yahoo và bất kỳ dịch vụ email nào khác trong một giao diện duy nhất. Phần mềm hoàn toàn miễn phí, không có quảng cáo và được cập nhật thường xuyên.",
		'url'      => 'https://www.thunderbird.net/',
		'download' => 'https://www.thunderbird.net/download/',
	],
	[
		'id'       => '7-zip',
		'name'     => '7-Zip',
		'cat'      => 'tien-ich',
		'desc'     => 'Trình nén và giải nén tập tin miễn phí, tỷ lệ nén cao, hỗ trợ nhiều định dạng.',
		'intro'    => "7-Zip là trình nén và giải nén tập tin mã nguồn mở, hoàn toàn miễn phí. Phần mềm hỗ trợ hầu hết các định dạng nén phổ biến: 7z, ZIP, RAR, TAR, GZIP và nhiều định dạng khác.\n\n7-Zip nổi bật với tỷ lệ nén cao, đặc biệt ở định dạng 7z riêng của nó, giúp tiết kiệm dung lượng lưu trữ và băng thông khi chia sẻ file. Phần mềm tích hợp vào menu chuột phải của Windows Explorer, giúp thao tác nén/giải nén nhanh chóng và thuận tiện.",
		'url'      => 'https://www.7-zip.org/',
		'download' => 'https://www.7-zip.org/download.html',
	],
	[
		'id'       => 'sharex',
		'name'     => 'ShareX',
		'cat'      => 'tien-ich',
		'desc'     => 'Chụp màn hình, quay video màn hình miễn phí, mã nguồn mở, nhiều tính năng mạnh mẽ.',
		'intro'    => "ShareX là công cụ chụp màn hình và quay video màn hình mã nguồn mở, hoàn toàn miễn phí. Đây là một trong những phần mềm chụp màn hình mạnh mẽ nhất hiện nay.\n\nPhần mềm cho phép bạn chụp ảnh màn hình toàn bộ, một vùng chọn, một cửa sổ hoặc cuộn trang web. Ngoài ra, ShareX còn hỗ trợ quay video màn hình, tạo ảnh GIF động, nhận dạng văn bản (OCR) và tự động tải lên nhiều dịch vụ lưu trữ khác nhau như Imgur, Google Photos, Dropbox.",
		'url'      => 'https://getsharex.com/',
		'download' => 'https://getsharex.com/download/',
	],
	[
		'id'       => 'ccleaner',
		'name'     => 'CCleaner',
		'cat'      => 'tien-ich',
		'desc'     => 'Công cụ dọn dẹp và tối ưu hệ thống Windows phổ biến, giúp máy tính chạy nhanh hơn.',
		'intro'    => "CCleaner là công cụ dọn dẹp hệ thống phổ biến, giúp bạn giải phóng dung lượng ổ cứng và tăng tốc máy tính. Phần mềm quét và xóa các file tạm thời, cache trình duyệt, lịch sử duyệt web và nhiều dữ liệu không cần thiết khác.\n\nCCleaner còn có trình dọn dẹp registry, quản lý các chương trình khởi động cùng Windows và gỡ cài đặt phần mềm. Những tính năng này giúp máy tính khởi động và hoạt động nhanh hơn, ổn định hơn sau thời gian dài sử dụng.",
		'url'      => 'https://www.ccleaner.com/',
		'download' => 'https://www.ccleaner.com/download',
	],
	[
		'id'       => 'vlc',
		'name'     => 'VLC Media Player',
		'cat'      => 'media',
		'desc'     => 'Trình phát đa phương tiện mã nguồn mở, phát được hầu hết mọi định dạng mà không cần codec.',
		'intro'    => "VLC Media Player là trình phát đa phương tiện mã nguồn mở, có khả năng phát hầu hết mọi định dạng video và âm thanh mà không cần cài thêm codec. Đây là trình phát media được ưa chuộng nhất thế giới với hơn 3 tỷ lượt tải về.\n\nVLC hỗ trợ phát đĩa DVD, CD, streaming trực tuyến, xem phim từ file torrent và nhiều định dạng file khác nhau. Phần mềm nhẹ, ổn định và có sẵn trên tất cả các nền tảng: Windows, macOS, Linux, Android và iOS.",
		'url'      => 'https://www.videolan.org/vlc/',
		'download' => 'https://www.videolan.org/vlc/download-windows.html',
	],
	[
		'id'       => 'affinity',
		'name'     => 'Affinity',
		'cat'      => 'media',
		'desc'     => 'Bộ ứng dụng thiết kế đồ họa chuyên nghiệp (Photo, Designer, Publisher) với chi phí hợp lý.',
		'intro'    => "Affinity là bộ ứng dụng thiết kế đồ họa chuyên nghiệp của Serif, bao gồm Affinity Photo (chỉnh sửa ảnh), Affinity Designer (thiết kế vector) và Affinity Publisher (dàn trang). Với hiệu năng vượt trội nhờ tận dụng sức mạnh GPU, Affinity mang đến trải nghiệm mượt mà ngay cả khi làm việc với file lớn.\n\nĐây là lựa chọn thay thế tuyệt vời cho các phần mềm thiết kế đắt tiền, với chính sách mua một lần sử dụng vĩnh viễn, không thuê bao. Affinity hỗ trợ đầy đủ các định dạng file phổ biến và có bản dùng thử miễn phí để bạn trải nghiệm trước khi mua.",
		'url'      => 'https://affinity.serif.com/',
		'download' => null,
	],
	[
		'id'       => 'davinci-resolve',
		'name'     => 'DaVinci Resolve',
		'cat'      => 'media',
		'desc'     => 'Phần mềm dựng phim và chỉnh màu chuyên nghiệp. Bản miễn phí cực kỳ mạnh mẽ.',
		'intro'    => "DaVinci Resolve là phần mềm dựng phim và chỉnh màu chuyên nghiệp của Blackmagic Design, được sử dụng trong nhiều sản phẩm điện ảnh Hollywood. Phiên bản miễn phí đã bao gồm hầu hết các tính năng mạnh mẽ.\n\nBạn có thể dựng phim đa luồng, chỉnh màu chuyên sâu, thêm hiệu ứng hình ảnh, chỉnh sửa âm thanh (Fairlight) và xuất bản với chất lượng lên đến 4K mà không tốn bất kỳ chi phí nào. Đây là lựa chọn hàng đầu cho các nhà làm phim độc lập, youtuber và người mới bắt đầu học dựng phim.",
		'url'      => 'https://www.blackmagicdesign.com/products/davinciresolve/',
		'download' => 'https://www.blackmagicdesign.com/support/',
	],
	[
		'id'       => 'audacity',
		'name'     => 'Audacity',
		'cat'      => 'media',
		'desc'     => 'Phần mềm ghi âm và chỉnh sửa âm thanh mã nguồn mở. Đơn giản, mạnh mẽ, miễn phí.',
		'intro'    => "Audacity là phần mềm ghi âm và chỉnh sửa âm thanh đa luồng, mã nguồn mở và hoàn toàn miễn phí. Đây là công cụ xử lý âm thanh được sử dụng rộng rãi bởi cả người mới bắt đầu và chuyên gia.\n\nBạn có thể ghi âm từ nhiều nguồn khác nhau (micro, line-in), cắt ghép, trộn âm thanh và thêm nhiều hiệu ứng. Audacity hỗ trợ nhiều định dạng âm thanh phổ biến như WAV, MP3, FLAC, OGG. Phần mềm phù hợp cho việc ghi podcast, chỉnh sửa nhạc và xử lý âm thanh cơ bản.",
		'url'      => 'https://www.audacityteam.org/',
		'download' => 'https://www.audacityteam.org/download/',
	],
	[
		'id'       => 'chrome',
		'name'     => 'Google Chrome',
		'cat'      => 'mang',
		'desc'     => 'Trình duyệt web nhanh, an toàn, phổ biến nhất thế giới. Đồng bộ trên mọi thiết bị.',
		'intro'    => "Google Chrome là trình duyệt web phổ biến nhất thế giới, nổi bật với tốc độ nhanh, giao diện đơn giản và bảo mật cao. Chrome được xây dựng trên nền tảng Chromium mã nguồn mở, liên tục được cập nhật và cải tiến.\n\nChrome hỗ trợ đồng bộ hóa bookmark, lịch sử, mật khẩu và tiện ích trên tất cả các thiết bị qua tài khoản Google. Kho tiện ích mở rộng phong phú trên Chrome Web Store giúp bạn tùy biến trình duyệt theo nhu cầu riêng. Ngoài ra, Chrome còn có tính năng bảo vệ chống lừa đảo và phần mềm độc hại tích hợp.",
		'url'      => 'https://www.google.com/chrome/',
		'download' => 'https://www.google.com/chrome/',
	],
	[
		'id'       => 'ultraviewer',
		'name'     => 'UltraViewer',
		'cat'      => 'mang',
		'desc'     => 'Phần mềm điều khiển máy tính từ xa miễn phí, dễ sử dụng, hỗ trợ truyền file và chat.',
		'intro'    => "UltraViewer là phần mềm điều khiển máy tính từ xa miễn phí, cho phép bạn kết nối và điều khiển máy tính ở bất kỳ đâu chỉ với một mã kết nối. Phần mềm đơn giản, dễ sử dụng, không yêu cầu cấu hình phức tạp.\n\nUltraViewer hỗ trợ truyền file qua lại giữa hai máy, chat trực tiếp và điều chỉnh chất lượng hình ảnh để phù hợp với tốc độ kết nối internet. Phần mềm rất hữu ích cho việc hỗ trợ kỹ thuật từ xa, dạy học trực tuyến hoặc làm việc từ xa.",
		'url'      => 'https://www.ultravier.com/',
		'download' => 'https://www.ultravier.com/download.html',
	],
	[
		'id'       => 'zalo',
		'name'     => 'Zalo',
		'cat'      => 'mang',
		'desc'     => 'Ứng dụng nhắn tin, gọi điện miễn phí phổ biến nhất Việt Nam với hơn 70 triệu người dùng.',
		'intro'    => "Zalo là ứng dụng nhắn tin và gọi điện miễn phí phổ biến nhất tại Việt Nam, với hơn 70 triệu người dùng. Được phát triển bởi VNG, Zalo hiểu rõ nhu cầu của người dùng Việt và liên tục cải tiến để mang lại trải nghiệm tốt nhất.\n\nZalo cung cấp đầy đủ các tính năng: nhắn tin văn bản, gọi thoại và gọi video chất lượng cao, chia sẻ file đa phương tiện, gửi ảnh và sticker. Ngoài ra còn có Zalo Pay, Zalo OA dành cho doanh nghiệp, Zalo Mini App và nhiều tiện ích giải trí khác. Zalo có mặt trên Windows, macOS, Android và iOS.",
		'url'      => 'https://zalo.me/',
		'download' => 'https://zalo.me/download',
	],
	[
		'id'       => 'avast',
		'name'     => 'Avast Free Antivirus',
		'cat'      => 'bao-mat',
		'desc'     => 'Phần mềm diệt virus miễn phí hàng đầu thế giới, bảo vệ máy tính toàn diện trước mọi mối đe dọa.',
		'intro'    => "Avast Free Antivirus là phần mềm bảo vệ máy tính miễn phí hàng đầu thế giới với hơn 400 triệu người dùng. Avast cung cấp khả năng bảo vệ toàn diện trước virus, phần mềm độc hại, ransomware, lừa đảo trực tuyến và các mối đe dọa mới nhất.\n\nPhần mềm có giao diện trực quan, dễ sử dụng và thường xuyên cập nhật cơ sở dữ liệu virus để đảm bảo an toàn tối đa. Avast còn có các tính năng bổ sung như tường lửa thông minh, bảo vệ web, quét lỗ hổng Wi-Fi và trình quản lý mật khẩu tích hợp.",
		'url'      => 'https://www.avast.com/',
		'download' => 'https://www.avast.com/download-antivirus',
	],
];

$COLORS = [
	'#6366f1',
	'#f97316',
	'#22c55e',
	'#a855f7',
	'#ec4899',
];
